CREATE DATABASE QLTHUVIEN
USE QLTHUVIEN

CREATE TABLE DOCGIA(
	MADG CHAR(10),
	HO NVARCHAR(20),
	TENLOT NVARCHAR(30),
	TEN NVARCHAR(20),
	NGAYSINH DATE
	PRIMARY KEY(MADG)
)
CREATE TABLE NGUOILON
(
	MADG CHAR(10),
	SONHA CHAR(10),
	DUONG NVARCHAR(50),
	QUAN VARCHAR(20),
	SDT CHAR(10),
	HANSD DATE
	PRIMARY KEY (MADG)
)

ALTER TABLE NGUOILON
ADD CONSTRAINT FK_NGUOILON_DOCGIA FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG)

CREATE TABLE TREEM (
	MADG CHAR(10),
	MADG_NL CHAR(10)
	PRIMARY KEY(MADG)	
)

ALTER TABLE TREEM
ADD CONSTRAINT FK_TREEM_DOCGIA FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG)
ALTER TABLE TREEM
ADD CONSTRAINT FK_TREEM_NGUOILON FOREIGN KEY (MADG) REFERENCES NGUOILON(MADG)

CREATE TABLE TUASACH(
	MATS CHAR(10),
	TUASACH NVARCHAR(50),
	TACGIA NVARCHAR(50),
	TOMTAT NVARCHAR(100),
	PRIMARY KEY(MATS)
)

CREATE TABLE DAUSACH(
	ISBN CHAR(5),
	MATS CHAR(10),
	NGONNGU NVARCHAR(20),
	BIA NVARCHAR(20),
	TRANGTHAI CHAR(5) CHECK(TRANGTHAI IN ('YES','NO')),
	PRIMARY KEY (ISBN)
)

ALTER TABLE DAUSACH
ADD CONSTRAINT FK_DAUSACH_TUASACH FOREIGN KEY (MATS) REFERENCES TUASACH(MATS)

CREATE TABLE CUONSACH(
	ISBN CHAR(5),
	MACS CHAR(10),
	TINHTRANG CHAR(5) CHECK(TINHTRANG IN('YES','NO'))
	PRIMARY KEY (MACS)
) 

ALTER TABLE CUONSACH
ADD CONSTRAINT FK_CUONSACH_DAUSACH FOREIGN KEY (ISBN) REFERENCES DAUSACH(ISBN)

CREATE TABLE MUON(
	MACS CHAR(10),
	MADG CHAR(10),
	PRIMARY KEY(MACS,MADG)
)

ALTER TABLE MUON
ADD CONSTRAINT FK_MUON_DOCGIA FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG)
ALTER TABLE MUON
ADD CONSTRAINT FK_MUON_CUONSACH FOREIGN KEY (MACS) REFERENCES CUONSACH(MACS)

CREATE TRIGGER TG_DELMUON
ON MUON
FOR DELETE
AS
BEGIN 
	DECLARE @MACS CHAR(10)
	SET @MACS = (SELECT MACS FROM deleted)
	UPDATE CUONSACH
	SET TINHTRANG = 'YES'
	WHERE MACS = @MACS
END

CREATE TRIGGER TG_INSMUON
ON MUON
FOR INSERT
AS
BEGIN 
	DECLARE @MACS CHAR(10)
	SET @MACS = (SELECT MACS FROM inserted)
	UPDATE CUONSACH
	SET TINHTRANG = 'NO'
	WHERE MACS = @MACS
END

CREATE TRIGGER TG_UPDCUONSACH
ON CUONSACH
FOR UPDATE
AS
BEGIN 
	DECLARE @TINHTRANG CHAR(5)
	DECLARE @ISBN CHAR(5)
	SET @ISBN = (SELECT ISBN FROM inserted)
	SET @TINHTRANG = (SELECT @TINHTRANG FROM inserted)
	UPDATE DAUSACH
	SET TRANGTHAI = @TINHTRANG
	WHERE ISBN = @ISBN
END



CREATE TRIGGER TG_INFOTHONGBAO
ON TUASACH
FOR INSERT, UPDATE
AS
BEGIN
	PRINT N'ĐÃ THÊM TỰA SÁCH MỚI'
	ROLLBACK TRAN
END


CREATE TRIGGER TG_KIEMTRATRUNG1
ON TUASACH
FOR INSERT
AS
BEGIN
	DECLARE @TUASACH NVARCHAR(50)
	SELECT @TUASACH =TUASACH 
	FROM INSERTED
	IF(@TUASACH IN (SELECT TUASACH FROM TUASACH))
		PRINT N'BỊ TRÙNG TỰA SÁCH'
END

CREATE TRIGGER TG_SUASACH
ON TUASACH
FOR UPDATE
AS
	DECLARE @TACGIACU NVARCHAR(50), @TACGIAMOI NVARCHAR(50)
	SET @TACGIACU = (SELECT TACGIA FROM deleted)
	SET @TACGIAMOI = (SELECT TACGIA FROM INSERTED)
	SELECT MATS
	FROM TUASACH
	WHERE TACGIA = @TACGIAMOI
	PRINT N'TÊN TÁC GIẢ VỪA ĐƯỢC SỬA' + @TACGIAMOI
	PRINT N'TÊN TÁC GIẢ ĐÃ SỬA' + @TACGIACU

CREATE TRIGGER TG_KIEMTRATRUNG2
ON TUASACH
FOR INSERT
AS
BEGIN
	DECLARE @TUASACH NVARCHAR(50)
	SELECT @TUASACH =TUASACH 
	FROM INSERTED
	IF(@TUASACH IN (SELECT TUASACH FROM TUASACH))
	BEGIN
		PRINT N'BỊ TRÙNG TỰA SÁCH'
		ROLLBACK
	END
END