CREATE DATABASE QUANLYSACH
USE QUANLYSACH
--TẠO CÁC BẢNG
CREATE TABLE NHOMSACH
(
	MANHOM CHAR(5),
	TENNHOM NVARCHAR(25),
	PRIMARY KEY(MANHOM)
)
CREATE TABLE NHANVIEN
(
	MANV CHAR(5),
	HOTOT NVARCHAR(25),
	TENNV NVARCHAR(10),
	PHAI NVARCHAR(3),
	NGAYSINH SMALLDATETIME,
	DIACHI NVARCHAR(40),
	PRIMARY KEY(MANV)
)

CREATE TABLE DANHMUCSACH
(
	MASACH CHAR(5),
	TENSACH NVARCHAR(40),
	TACGIA NVARCHAR(20),
	MANHOM CHAR(5),
	DONGIA NUMERIC(5),
	SOLUONGTON NUMERIC(5),
	PRIMARY KEY(MASACH)
)
CREATE TABLE HOADON
(
	MAHD CHAR(5),
	NGAYBAN SMALLDATETIME,
	MANV CHAR(5),
	PRIMARY KEY(MAHD)
)
CREATE TABLE CHITIETHOADON
(
	MAHD CHAR(5),
	MASACH CHAR(5),
	SOLUONG NUMERIC(5),
	PRIMARY KEY(MAHD,MASACH)
)
--TẠO KHÓA NGOẠI CÁC BẢNG
ALTER TABLE DANHMUCSACH
ADD CONSTRAINT FK_DANHMUCSACH_MANHOM FOREIGN KEY(MANHOM) REFERENCES NHOMSACH(MANHOM)
ALTER TABLE HOADON
ADD CONSTRAINT FK_HODON_MANV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_MAHD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_MASACH FOREIGN KEY(MASACH) REFERENCES DANHMUCSACH(MASACH)
--NHẬP LIỆU VÀO CÁC BẢNG
INSERT INTO NHOMSACH VALUES
('NS01',N'CÔNG NGHỆ THÔNG TIN'),
('NS02',N'TÀI CHÍNH KẾ TOÁN')
---BẢNG NHÂN VIÊN
SET DATEFORMAT DMY
INSERT INTO NHANVIEN VALUES
('NV01',N'LÊ NGUYỄN THẢO',N'VY',N'NỮ','04/11/2000',N'LONG AN'),
('NV02',N'TRẦN HOÀNG',N'LONG',N'NAM','05/02/1988',N'TP.HCM')
--DANH MỤC SÁCH
INSERT INTO DANHMUCSACH VALUES
('MS01',N'NGÔN NGỮ LẬP TRÌNH',N'TRẦN MINH KHANG','NS01',50000,20),
('MS02',N'LUẬT KINH TẾ',N'TRẦN BÍCH THỦY','NS02',40000,15)
--HÓA ĐƠN
SET DATEFORMAT DMY
INSERT INTO HOADON VALUES
('HD01','5/5/2010','NV01'),
('HD02','5/8/2009','NV01'),
('HD03','5/5/2014','NV02')
--CHI TIẾT HÓA ĐƠN
INSERT INTO CHITIETHOADON VALUES
('HD01','MS01',2),
('HD01','MS02',3)

CREATE TRIGGER BAI1_1
ON NHOMSACH
FOR INSERT 
AS 
DECLARE @NUMBER INT
SET @NUMBER = (SELECT COUNT(*) FROM INSERTED)
PRINT N'CÓ ' + CONVERT(NVARCHAR,@NUMBER)+ N' mẫu tin được chèn'

INSERT INTO NHOMSACH VALUES
('NS03', N'QUẢN TRỊ KINH DOANH')

CREATE TABLE HOADON_Luu
(
	MAHD CHAR(5),
	NGAYBAN SMALLDATETIME,
	MANV CHAR(5),
	PRIMARY KEY(MAHD)
)
DROP TRIGGER BAI1_2
CREATE TRIGGER BAI1_2
ON HOADON
AFTER INSERT
AS 
BEGIN
DECLARE @MANV CHAR(5)
DECLARE @NGAYBAN SMALLDATETIME
DECLARE @MAHD CHAR(5)
SET @MAHD = (SELECT MANV FROM INSERTED)
SET @NGAYBAN = (SELECT NGAYBAN FROM INSERTED)
SET @MAHD = (SELECT MAHD FROM INSERTED)
INSERT INTO HOADON_Luu VALUES
(@MAHD, @NGAYBAN, @MANV)
END

INSERT INTO HOADON VALUES
('HD05',GETDATE(),'NV02')

ALTER TABLE HOADON
ADD TONGTRIGIA NUMERIC(10)

DROP TRIGGER BAI1_3

CREATE TRIGGER BAI1_3
ON CHITIETHOADON
FOR INSERT, DELETE, UPDATE
AS
BEGIN
	UPDATE HOADON 
	SET TONGTRIGIA = (SELECT SUM(SOLUONG*DONGIA) FROM CHITIETHOADON C, DANHMUCSACH D 
	WHERE C.MASACH = D.MASACH AND HOADON.MAHD = C.MAHD)
END

UPDATE CHITIETHOADON
SET SOLUONG = 5
WHERE MASACH = 'MS01'

ALTER TABLE CHITIETHOADON
ADD GIABAN NUMERIC(5)

DROP TRIGGER BAI1_4
CREATE TRIGGER BAI1_4
ON CHITIETHOADON
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @GIABAN INT
	DECLARE @MASACH CHAR(5)
	SET @GIABAN = (SELECT GIABAN FROM INSERTED)
	SET @MASACH = (SELECT MASACH FROM INSERTED)
	IF (@GIABAN NOT IN (SELECT DONGIA  FROM DANHMUCSACH WHERE @MASACH = MASACH))
	BEGIN 
	PRINT N'NHẬP SAI GIÁ BÁN'
	ROLLBACK TRAN
	END
END

INSERT INTO CHITIETHOADON VALUES
('HD05','MS01',3 ,50000)

UPDATE CHITIETHOADON
SET GIABAN = 5000
WHERE MAHD = 'HD05'

ALTER TABLE HOADON
ADD NGAYLAP SMALLDATETIME

DROP TRIGGER BAI1_5
CREATE TRIGGER BAI1_5
ON HOADON
FOR UPDATE, INSERT
AS
BEGIN
	DECLARE @NGAYBAN SMALLDATETIME
	DECLARE @NGAYLAP SMALLDATETIME
	SET @NGAYBAN = (SELECT NGAYBAN FROM INSERTED)
	SET @NGAYLAP = (SELECT NGAYLAP FROM INSERTED)
	IF(@NGAYLAP > @NGAYBAN)
	BEGIN 
	PRINT N'NGAY LẬP LỚN HƠN NGÀY BÁN'
	ROLLBACK TRAN
	END
END
SET DATEFORMAT DMY

INSERT INTO HOADON VALUES
('HD04', '1/4/2020','NV02',0,'23/02/2020')