CREATE DATABASE QUANLYSINHV

USE QUANLYSINHV

--2.1
CREATE TABLE LOP(
	MALOP VARCHAR(10) PRIMARY KEY,
	TENLOP NVARCHAR(30) UNIQUE
)

CREATE TABLE SINHVIEN(
	HOTENSV NVARCHAR(50),
	MASV VARCHAR(10) PRIMARY KEY,
	NGAYSINH DATETIME DEFAULT '1/1/2001',
	MALOP VARCHAR(10)
)

ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_MALOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

CREATE TABLE MONHOC(
	TENMH NVARCHAR(30) UNIQUE,
	MAMH VARCHAR(10) PRIMARY KEY,
)

CREATE TABLE KETQUA(
	MASV VARCHAR(10),
	MAMH VARCHAR(10),
	DIEM FLOAT CHECK(DIEM BETWEEN 0 AND 10),
	PRIMARY KEY(MASV, MAMH)
)

ALTER TABLE KETQUA
ADD CONSTRAINT FK_KETQUA_MASV FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)

ALTER TABLE KETQUA
ADD CONSTRAINT FK_KETQUA_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)


CREATE FUNCTION	CAUA()
RETURNS TABLE 
AS RETURN (select LEFT(HOTENSV,CHARINDEX(' ',HOTENSV)) AS N'HỌ',REVERSE(RIGHT(REVERSE(RIGHT(HOTENSV, CHARINDEX (' ',HOTENSV)+1)),CHARINDEX(' ',REVERSE(RIGHT(HOTENSV, CHARINDEX (' ',HOTENSV)+1))))) as Holot, REVERSE(LEFT(REVERSE(HOTENSV),CHARINDEX(' ', REVERSE(HOTENSV)))) AS 'TÊN' FROM SINHVIEN)

CREATE FUNCTION CAUB()
RETURNS TABLE
AS RETURN (SELECT HOTENSV, NGAYSINH, DATENAME(DW,NGAYSINH) AS N'THỨ' FROM SINHVIEN)

CREATE FUNCTION CAUC()
RETURNS TABLE
AS RETURN (SELECT S.MASV, HOTENSV, STR(AVG(DIEM),5,1) AS N'ĐIỂM' FROM SINHVIEN S, KETQUA K WHERE S.MASV = K .MASV GROUP BY S.MASV, HOTENSV HAVING  AVG(DIEM)>=5)

CREATE FUNCTION CAUD(@MASV CHAR(10))
RETURNS TABLE
AS RETURN (SELECT K.MALOP, TENLOP FROM LOP K, SINHVIEN S WHERE S.MASV = @MASV AND S.MALOP = K.MALOP)

CREATE FUNCTION CAUE()
RETURNS TABLE 
AS RETURN (SELECT M.MAMH, M.TENMH, STR(AVG(DIEM),5,2) AS N'ĐIỂM TB' FROM MONHOC M,KETQUA K WHERE K.MAMH = M.MAMH GROUP BY M.MAMH, M.TENMH)

CREATE FUNCTION CAUF(@MALOP CHAR(10))
RETURNS INT
AS
BEGIN
	RETURN (SELECT TOP(1) AVG(DIEM) FROM KETQUA K, SINHVIEN S WHERE S.MASV = K.MASV AND S.MALOP = @MALOP GROUP BY HOTENSV ORDER BY AVG(DIEM) DESC)
END

SELECT DBO.CAUF('CNTT')

CREATE FUNCTION BOTROG(@MAKHOA NVARCHAR(10))
RETURNS VARCHAR(10)
AS BEGIN
RETURN (SELECT TOP(1) MALOP FROM LOP ORDER BY MALOP DESC)
END

DROP PROC DBO.CAUG
CREATE PROC CAUG(@KHOA VARCHAR(10))
AS
BEGIN
	DECLARE @MALOP VARCHAR(10)
	DECLARE @TEMP  VARCHAR(10)
	SET @TEMP = DBO.BOTROG(@KHOA)
	DECLARE @STT INT
	SET @STT = CAST(RIGHT(@TEMP,3) AS INT) +1
	if @stt < 10
	begin
	set @MALOP = @KHOA+ '00'  + cast (@stt as varchar(1))
	end
	else if @stt < 100
	begin
	set @MALOP = @KHOA +'0' +cast (@stt as varchar(2))
	enD
	else
	begin
	set @MALOP = @KHOA+ cast (@stt as varchar(3))
	end
	INSERT INTO LOP VALUES (@MALOP,@KHOA)
END

EXEC DBO.CAUG 'CNTT'

