CREATE DATABASE QUANLYNGK

USE QUANLYNGK

CREATE TABLE NHASANXUAT(
	MANSX VARCHAR(10),
	TENNSX NVARCHAR(30),
	PRIMARY KEY (MANSX)
)

CREATE TABLE NUOCGIAIKHAT(
	MANGK VARCHAR(10),
	TENNGK NVARCHAR(30),
	DVT NVARCHAR(10),
	SOLUONG INT,
	DONGIA INT,
	MALOAI VARCHAR(10),
	PRIMARY KEY (MANGK)
)

CREATE TABLE HOADON(
	SOHD VARCHAR(10),
	NGAYLAP DATE,
	PRIMARY KEY (SOHD)
)

CREATE TABLE CHITIETHOADON(
	SOHD VARCHAR(10),
	MANGK VARCHAR(10),
	SOLUONG INT,
	DONGIA INT,
	PRIMARY KEY (SOHD, MANGK)
)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_SOHD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_MANGK FOREIGN KEY (MANGK) REFERENCES NUOCGIAIKHAT(MANGK)

--LAB 8 BÀI 5
--CÂU A:
CREATE FUNCTION CAU5_A()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @SOHD VARCHAR(10), @NGAY VARCHAR(10)
	SET @SOHD = (SELECT MAX(SOHD) FROM HOADON)
	SET @NGAY = CONVERT(VARCHAR(10), GETDATE(), 103)
	SET @NGAY = SUBSTRING(@NGAY,1,2) + SUBSTRING(@NGAY,4,2) + SUBSTRING(@NGAY, 9,2)
	IF(@NGAY = SUBSTRING(@SOHD,1,6))
		BEGIN
			DECLARE @STT INT
			SET @STT = CONVERT(INT, SUBSTRING(@SOHD, 7, LEN(@SOHD) - 6)) + 1
			RETURN @NGAY + CAST(@STT AS VARCHAR(4))
		END
	RETURN @NGAY + '1'
END

SELECT DBO.CAU5_A()

--CÂU B:
CREATE PROCEDURE CAU5_B
AS
BEGIN
	DECLARE @SOHD VARCHAR(10)
	SET @SOHD = DBO.CAU5_A()
	INSERT INTO HOADON VALUES (@SOHD, GETDATE())
END

EXECUTE CAU5_B

--CÂU C:
CREATE PROCEDURE CAU5_C(@MANSX VARCHAR(10), @TENNGK NVARCHAR(30), @DVT NVARCHAR(10), @SOLUONG INT, @DONGIA INT)
AS
BEGIN
	DECLARE @MANGK VARCHAR(10)
	SET @MANGK = (SELECT MAX(MANGK) FROM NUOCGIAIKHAT WHERE MALOAI = @MANSX)
	IF(@MANGK IS NOT NULL)
		BEGIN
			DECLARE @STT INT, @MAMOI VARCHAR(10)
			SET @STT = CONVERT(INT, SUBSTRING(@MANGK, LEN(@MANSX) + 1, 3)) + 1
			IF(@STT < 10)
				SET @MAMOI = @MANSX + '00' + CAST(@STT AS VARCHAR(1))
			ELSE IF(@STT < 100)
				SET @MAMOI = @MANSX + '0' + CAST(@STT AS VARCHAR(2))
			ELSE
				SET @MAMOI = @MANSX + CAST(@STT AS VARCHAR(3))
			INSERT INTO NUOCGIAIKHAT VALUES (@MAMOI, @TENNGK, @DVT, @SOLUONG, @DONGIA, @MANSX)
		END
	ELSE
		INSERT INTO NUOCGIAIKHAT VALUES (@MANSX + '001', @TENNGK, @DVT, @SOLUONG, @DONGIA, @MANSX)
END

EXECUTE CAU5_C 'COCA',N'COCA COLA CHANH','CHAI','300','8000'

--CÂU D:
CREATE PROCEDURE CAU5_D(@SOHD VARCHAR(10), @MANGK VARCHAR(10), @SOLUONG INT)
AS
BEGIN
	DECLARE @SOLUONGSP INT, @DONGIA INT
	SET @SOLUONGSP = (SELECT SOLUONG FROM NUOCGIAIKHAT WHERE MANGK = @MANGK)
	SET @DONGIA = (SELECT DONGIA FROM NUOCGIAIKHAT WHERE MANGK = @MANGK)
	IF(@SOLUONG <= @SOLUONGSP)
		INSERT INTO CHITIETHOADON VALUES (@SOHD, @MANGK, @SOLUONG, @DONGIA * 1.5)
	ELSE
		PRINT N'KHÔNG ĐỦ SỐ LƯỢNG SẢN PHẨM'

END

EXECUTE CAU5_D '1303213','PEP001',1400

--CÂU E:
CREATE FUNCTION CAU5_E(@SOHD VARCHAR(10))
RETURNS INT
AS
BEGIN
	DECLARE @TONGTIEN INT
	SET @TONGTIEN = (SELECT SUM(DONGIA) 
					 FROM CHITIETHOADON 
					 WHERE SOHD = @SOHD
					 GROUP BY SOHD)
	RETURN @TONGTIEN
END

SELECT DBO.CAU5_E('1303213') AS N'TỔNG TIỀN'

--CÂU F:
CREATE FUNCTION CAU5_F()
RETURNS TABLE
AS
	RETURN SELECT DISTINCT NGK.MANGK, TENNGK, NGAYLAP AS N'NGÀY BÁN'
		   FROM NUOCGIAIKHAT NGK, CHITIETHOADON CTHD, HOADON HD
		   WHERE NGK.MANGK = CTHD.MANGK AND HD.SOHD = CTHD.SOHD
				 AND MONTH(HD.NGAYLAP) = 3 AND YEAR(HD.NGAYLAP) = 2021


SELECT * FROM CAU5_F()