CREATE DATABASE QUANLYSINHVIEN

USE QUANLYSINHVIEN

--2.1
CREATE TABLE KHOA(
	MAKHOA VARCHAR(10) PRIMARY KEY,
	TENKHOA NVARCHAR(30) UNIQUE
)

CREATE TABLE SINHVIEN(
	HOSV NVARCHAR(30),
	TENSV NVARCHAR(30),
	MASV VARCHAR(10) PRIMARY KEY,
	NGAYSINH DATETIME DEFAULT '1/1/2001',
	PHAI NVARCHAR(5) CHECK(PHAI IN('NAM', N'NỮ')),
	MAKHOA VARCHAR(10)
)

ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

CREATE TABLE MONHOC(
	TENMH NVARCHAR(30) UNIQUE,
	MAMH VARCHAR(10) PRIMARY KEY,
	SOTIET INT CHECK(SOTIET > 0)
)

CREATE TABLE KETQUA(
	MASV VARCHAR(10),
	MAMH VARCHAR(10),
	LANTHI INT,
	DIEM FLOAT CHECK(DIEM BETWEEN 0 AND 10),
	PRIMARY KEY(MASV, MAMH, LANTHI)
)

ALTER TABLE KETQUA
ADD CONSTRAINT FK_KETQUA_MASV FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)

ALTER TABLE KETQUA
ADD CONSTRAINT FK_KETQUA_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

--2.2
--XÓA RÀNG BUỘC KHOA NGOẠI
ALTER TABLE KETQUA DROP FK_KETQUA_MASV

ALTER TABLE KETQUA DROP FK_KETQUA_MAMH

--2.3
ALTER TABLE SINHVIEN DROP FK_SINHVIEN_MAKHOA

--XÓA BẢNG
DROP TABLE KHOA

DROP TABLE MONHOC

--2.4
CREATE TABLE KHOA(
	MAKHOA VARCHAR(10) PRIMARY KEY,
	TENKHOA NVARCHAR(30) UNIQUE
)

CREATE TABLE MONHOC(
	TENMH NVARCHAR(30) UNIQUE,
	MAMH VARCHAR(10) PRIMARY KEY,
	SOTIET INT CHECK(SOTIET > 0)
)

ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE KETQUA
ADD CONSTRAINT FK_KETQUA_MASV FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)

ALTER TABLE KETQUA
ADD CONSTRAINT FK_KETQUA_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

--2.5: NHẬP DỮ LIỆU CHO BẢNG
--INSERT THEO TỪNG DÒNG
INSERT INTO KHOA VALUES ('AVAN', N'KHOA ANH VĂN')

--INSERT VÀO TẤT CẢ CÁC DÒNG CÙNG 1 LÚC
INSERT INTO KHOA VALUES
('CNTT', N'CÔNG NGHỆ THÔNG TIN'),
('DTVT', N'ĐIỆN TỬ VIỄN THÔNG'),
('QTKD', N'QUẢN TRỊ KINH DOANH')

SET DATEFORMAT DMY
INSERT INTO SINHVIEN VALUES
(N'TRẦN MINH', N'SƠN', 'S001','5/1/1985', 'NAM', 'CNTT')

INSERT INTO SINHVIEN VALUES
(N'NGUYỄN QUỐC', N'BẢO', 'S002','15/6/1985', 'NAM', 'CNTT'),
(N'PHAN ANH', N'TÙNG', 'S003','20/12/1985', 'NAM', 'QTKD'),
(N'BÙI THỊ ÁNH', N'THƯ', 'S004','1/2/1985', N'NỮ', 'QTKD'),
(N'LÊ THỊ LAN', N'ANH', 'S005','3/7/1985', N'NỮ', 'DTVT'),
(N'NGUYỄN THỊ', N'LAM', 'S006','25/11/1985', N'NỮ', 'DTVT'),
(N'PHAN THỊ', N'HÀ', 'S007','3/7/1985', N'NỮ', 'CNTT'),
(N'TRẦN THẾ', N'DŨNG', 'S008','21/10/1985', 'NAM', 'CNTT')

INSERT INTO MONHOC VALUES
(N'ANH VĂN', 'AV', 45),
(N'CƠ SỞ DỮ LIỆU', 'CSDL', 45),
(N'KỸ THUẬT LẬP TRÌNH', 'KTLT', 60),
(N'KẾ TOÁN TÀI CHÍNH', 'KTTC', 45),
(N'TOÁN CAO CẤP', 'TCC', 60),
(N'TIN HỌC VĂN PHÒNG', 'THVP', 30),
(N'TRÍ TUỆ NHÂN TẠO', 'TTNT', 45)

INSERT INTO KETQUA VALUES
('S001','CSDL',1,4),
('S001','TCC',1,6),
('S002','CSDL',1,3),
('S002','CSDL',2,6),
('S003','KTTC',1,5),
('S004','AV',1,8),
('S004','THVP',1,4),
('S004','THVP',2,8),
('S006','TCC',1,5),
('S007','AV',1,2),
('S007','AV',2,9),
('S007','KTLT',1,6),
('S008','AV',1,7)

--2.6
UPDATE MONHOC 
SET SOTIET = 30
WHERE TENMH = N'TRÍ TUỆ NHÂN TẠO'

--2.7
DELETE FROM KETQUA 
WHERE MASV = 'S001' 

--2.8
INSERT INTO KETQUA VALUES
('S001','CSDL',1,4),
('S001','TCC',1,6)

--2.9
UPDATE SINHVIEN
SET HOSV = N'NGUYỄN VĂN', TENSV = N'LÂM'
WHERE HOSV = N'NGUYỄN THỊ' AND TENSV = 'LAM'

--2.10
UPDATE SINHVIEN
SET MAKHOA = 'CNTT'
WHERE HOSV = N'LÊ THỊ LAN' AND TENSV = 'ANH'
