CREATE DATABASE QUANLYBANHANG

USE QUANLYBANHANG

--2.1)
CREATE TABLE NHANVIEN(
	MANHANVIEN VARCHAR(20) PRIMARY KEY,
	HO NVARCHAR(30),
	TEN NVARCHAR(20),
	NGAYSINH DATETIME,
	NGAYLAMVIEC DATETIME,
	DIACHI NVARCHAR(60),
	DIENTHOAI VARCHAR(12),
	LUONGCOBAN INT,
	PHUCAP INT
)

CREATE TABLE KHACHHANG(
	MAKHACHHANG VARCHAR(20) PRIMARY KEY,
	TENCONGTY NVARCHAR(30),
	TENGIAODICH NVARCHAR(30),
	DIACHI NVARCHAR(60),
	EMAIL VARCHAR(30),
	DIENTHOAI VARCHAR(12),
	FAX VARCHAR(12)
)

CREATE TABLE NHACUNGCAP(
	MACONGTY VARCHAR(20) PRIMARY KEY,
	TENCONGTY NVARCHAR(30),
	TENGIAODICH NVARCHAR(30),
	DIACHI NVARCHAR(60),
	DIENTHOAI VARCHAR(12),
	FAX VARCHAR(12),
	EMAIL VARCHAR(20)
)

CREATE TABLE LOAIHANG(
	MALOAIHANG VARCHAR(20) PRIMARY KEY,
	TENLOAIHANG NVARCHAR(30)
)

CREATE TABLE DONDATHANG(
	SOHOADON VARCHAR(10) PRIMARY KEY,
	MAKHACHHANG VARCHAR(20),
	MANHANVIEN VARCHAR(20),
	NGAYDATHANG DATETIME,
	NGAYGIAOHANG DATETIME,
	NGAYCHUYENHANG DATETIME,
	NOIGIAOHANG NVARCHAR(60)
)

ALTER TABLE DONDATHANG 
ADD CONSTRAINT FK_DONDATHANG_MAKHACHHANG FOREIGN KEY(MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)

ALTER TABLE DONDATHANG
ADD CONSTRAINT FK_DONDATHANG_MANHANVIEN FOREIGN KEY(MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)

CREATE TABLE MATHANG(
	MAHANG VARCHAR(20) PRIMARY KEY,
	TENHANG NVARCHAR(30),
	MACONGTY VARCHAR(20),
	MALOAIHANG VARCHAR(20),
	SOLUONG INT,
	DONVITINH VARCHAR(10),
	GIAHANG INT
)

ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_MACONGTY FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY)

ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_MALOAIHANG FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)

CREATE TABLE CHITIETDATHANG(
	SOHOADON VARCHAR(10),
	MAHANG VARCHAR(20),
	GIABAN INT,
	SOLUONG INT,
	MUCGIAMGIA INT,
	PRIMARY KEY(SOHOADON, MAHANG)
)

ALTER TABLE CHITIETDATHANG
ADD CONSTRAINT FK_CHITIETDATHANG_SOHOADON FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON)

ALTER TABLE CHITIETDATHANG
ADD CONSTRAINT FK_CHITIETDATHANG_MAHANG FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)


--2.2)
ALTER TABLE CHITIETDATHANG
ADD DEFAULT 1 FOR SOLUONG

ALTER TABLE CHITIETDATHANG
ADD DEFAULT 0 FOR MUCGIAMGIA

--2.3)
ALTER TABLE DONDATHANG
ADD CONSTRAINT CK_DONDATHANG_NGAYGIAO CHECK(NGAYDATHANG <= NGAYGIAOHANG AND NGAYDATHANG <= NGAYCHUYENHANG)

--2.4)
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_NHANVIEN_NGAYSINH CHECK(YEAR(GETDATE()) - YEAR(NGAYSINH) >= 18 AND YEAR(GETDATE()) - YEAR(NGAYSINH) <= 60)

--2.5) KHÔNG THỂ XÓA BẢNG NHACUNGCAP VÌ BẢNG MATHANG ĐANG CÓ RÀNG BUỘC KHÓA NGOẠI VỚI NÓ